sudo: required
services:
- docker
script:
- sed -i '/oom_kill_disable/d' docker-compose.yml
- echo 'Europe/Berlin' | MAILCOW_HOSTNAME=build.mailcow ./generate_config.sh
- docker-compose build
branches:
  only:
  - travis
